apiVersion: v1
kind: ConfigMap
metadata:
  name: titan-load
  namespace: default
data:
  init.sh: |
    #!/bin/sh
    apk update && apk upgrade && apk add curl
    while true
    do
      curl http://titan-app.default.svc.cluster.local/cpu/
      sleep 0.01
    done
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: titan-load
  namespace: default
  labels:
    app: titan-load
spec:
  replicas: 2
  selector:
    matchLabels:
      app: titan-load
  template:
    metadata:
      labels:
        app: titan-load
    spec:
      automountServiceAccountToken: false
      containers:
      - name: titan-load
        image: alpine:3.18.0
        imagePullPolicy: IfNotPresent
        command: ["/usr/bin/init.sh"]
        volumeMounts:
          - name: titan-load
            mountPath: /usr/bin/init.sh
            subPath: init.sh
        resources:
          requests:
            cpu: "150m"
            memory: "128Mi"
          limits:
            cpu: "150m"
            memory: "128Mi"
      volumes:
      - name: titan-load
        configMap:
          name: titan-load
          defaultMode: 0777