apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: test-application
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-application
  minReplicas: 1
  maxReplicas: 10000
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 20